CREATE DATABASE IF NOT EXISTS dinamica;
CREATE DATABASE IF NOT EXISTS estatica;
CREATE DATABASE IF NOT EXISTS proxy;
CREATE DATABASE IF NOT EXISTS comun;
CREATE DATABASE IF NOT EXISTS keycloak;


CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;